### ISSUE TITLE
There is no macOS or Linux release

### ISSUE THREAD

**Issue by vvoiner** [LDev-IX/ZEL#1]
In the readme you claim that this language is compatible with Linux or macOS, and yet there is no download for either of these operating systems. How come?

![image](https://user-images.githubusercontent.com/39580907/142947960-ccf63053-c597-49bd-93cd-3ca28b12f1d4.png)

**Comment by LDev-IX** [comment]
Yooo I didn't even notice XDD

I'm adding a release with application for each of those operating systems right now.
