### ISSUE TITLE
Commands only require one quotation mark

### ISSUE THREAD

**Issue by vvoiner** [LDev-IX/ZEL#2]
If you type a command with only one quotation mark at the beginning, everything after the quotation mark will still work correctly even though it isn't contained inside anything.

![image](https://user-images.githubusercontent.com/39580907/142997980-57ba5fc0-61ae-4855-a82f-ca344c2107d2.png)
![image](https://user-images.githubusercontent.com/39580907/142998035-72af713f-de7d-478e-a237-20ebd52aab95.png)

**Comment by LDev-IX** [comment]
Yes, but in the future there will be commands that require multiple arguments
And I don't really think that it works correctly because it doesn't print "aaa" and just prints "gfdsgsd"
I could change it to only work when the argument variable is contained in "" but why doe

**Comment by vvoiner** [comment]
well yeah but if u want to implement commands with multiple arguments you'd still need to seperate them with "" so they'd still need to be contained in those

ex. command "argument1" "argument2"

**Comment by LDev-IX** [comment]
Ight now the second quotation mark is required or you'll get an exception
