### ISSUE TITLE
if the wait command is incorrectly formatted the shell will crash instead of catching the exception

### ISSUE THREAD

**Issue by vvoiner** [LDev-IX/ZEL#3]
Putting in a number without quotation marks inside the wait command will result in the programme crashing instead of throwing an exception. This only happens with the wait command.

![image](https://user-images.githubusercontent.com/39580907/142998730-cc17920b-b986-4488-8e19-04709fba6535.png)
![image](https://user-images.githubusercontent.com/39580907/142998789-bf4c3b1a-92d4-4d3c-8be6-5147fc1b8370.png)

**Comment by LDev-IX** [comment]
Yeah, that's why you must use "" when you set a variable far an argument
I will fix that to throw some kind of exception
Thanks for reporting !
